name: meowmedic
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  sliding_clipped_nav_bar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bloblogin.png
    - assets/blobregis.png
    - assets/catgroup.png
